### PR TITLE
[WIP] Thread experiment

### PR DESCRIPTION
**Pull request by justinlittman**

### CODE REVIEW

**Comment by justinlittman** [comment]
In testing publications ETL for 50 people:
* 1 thread -> 101 seconds
* 2 threads -> 71 seconds
* 3 threads -> 63 seconds
* 4 threads -> 64 seconds

**Comment by mjgiarlo** [comment]
Awesome, @justinlittman. Can you fire this branch up against the full data set and let it go for a day or two to see how it behaves? Thanks!

**Comment by justinlittman** [comment]
Great idea, @mjgiarlo. Will do.

**Comment by mjgiarlo** [comment]
We are not pursuing this strategy in this work cycle. Closing PR. Please do not remove branch!

**Pull request closed without merging**
